insert into user_role(role, description) values ('ROLE_USER', 'default role for user');
insert into category(name) values ('bezmięsny');
insert into category(name) values ('wieprzowina');
insert into category(name) values ('drób');
insert into category(name) values ('wołowina');
insert into category(name) values ('ryba i owoce morza');
insert into category(name) values ('cielęcina');
insert into category(name) values ('jagnięcina');
insert into category(name) values ('baranina');
insert into category(name) values ('dziczyzna');
insert into category(name) values ('zupa');
insert into category(name) values ('szybki');
insert into category(name) values ('okazyjny');
insert into shop_section(section) values ('pieczywo');
insert into shop_section(section) values ('mięso/ryby');
insert into shop_section(section) values ('owoce/warzywa');
insert into shop_section(section) values ('nabiał/jaja');
insert into shop_section(section) values ('art. sypkie');
insert into shop_section(section) values ('słodycze/przekąski');
insert into shop_section(section) values ('kawa, herbata');
insert into shop_section(section) values ('przyprawy');
insert into shop_section(section) values ('mrożonki');
insert into shop_section(section) values ('alkohole');
insert into shop_section(section) values ('zdrowa żywność');
insert into shop_section(section) values ('kuchnie świata');
insert into shop_section(section) values ('napoje');
insert into shop_section(section) values ('chemia');
insert into shop_section(section) values ('do pieczenia');
insert into shop_section(section) values ('inne');
insert into shop_section(section) values ('konserwy');
insert into shop_section(section) values ('kosmetyki');
insert into shop_section(section) values ('dla dzieci');
insert into shop_section(section) values ('dla zwierząt');
insert into shop_section(section) values ('ogród');
insert into category_details(detail, category_id) values ('schab', '2');
insert into category_details(detail, category_id) values ('wieprz', '2');
insert into category_details(detail, category_id) values ('szynk', '2');
insert into category_details(detail, category_id) values ('biodrów', '2');
insert into category_details(detail, category_id) values ('golonka', '2');
insert into category_details(detail, category_id) values ('indy', '3');
insert into category_details(detail, category_id) values ('kaczk', '3');
insert into category_details(detail, category_id) values ('gęsi', '3');
insert into category_details(detail, category_id) values ('gęś', '3');
insert into category_details(detail, category_id) values ('drobio', '3');
insert into category_details(detail, category_id) values ('kurcz', '3');
insert into category_details(detail, category_id) values ('bażant', '3');
insert into category_details(detail, category_id) values ('przepiór', '3');
insert into category_details(detail, category_id) values ('perlicz', '3');
insert into category_details(detail, category_id) values ('wołow', '4');
insert into category_details(detail, category_id) values ('rozbratel', '4');
insert into category_details(detail, category_id) values ('antykrot', '4');
insert into category_details(detail, category_id) values ('ryb', '5');
insert into category_details(detail, category_id) values ('karp', '5');
insert into category_details(detail, category_id) values ('pstrąg', '5');
insert into category_details(detail, category_id) values ('łoso', '5');
insert into category_details(detail, category_id) values ('dorsz', '5');
insert into category_details(detail, category_id) values ('pang', '5');
insert into category_details(detail, category_id) values ('sandacz', '5');
insert into category_details(detail, category_id) values ('dorad', '5');
insert into category_details(detail, category_id) values ('makrel', '5');
insert into category_details(detail, category_id) values ('tuńcz', '5');
insert into category_details(detail, category_id) values ('halibut', '5');
insert into category_details(detail, category_id) values ('morszcz', '5');
insert into category_details(detail, category_id) values ('śled', '5');
insert into category_details(detail, category_id) values ('matijas', '5');
insert into category_details(detail, category_id) values ('flądr', '5');
insert into category_details(detail, category_id) values ('węgorz', '5');
insert into category_details(detail, category_id) values ('jesiotr', '5');
insert into category_details(detail, category_id) values ('nototen', '5');
insert into category_details(detail, category_id) values ('plamiak', '5');
insert into category_details(detail, category_id) values ('krewet', '5');
insert into category_details(detail, category_id) values ('limand', '5');
insert into category_details(detail, category_id) values ('mint', '5');
insert into category_details(detail, category_id) values ('tilap', '5');
insert into category_details(detail, category_id) values ('szczup', '5');
insert into category_details(detail, category_id) values ('sum', '5');
insert into category_details(detail, category_id) values ('kara', '5');
insert into category_details(detail, category_id) values ('miętus', '5');
insert into category_details(detail, category_id) values ('krab', '5');
insert into category_details(detail, category_id) values ('homar', '5');
insert into category_details(detail, category_id) values ('rak', '5');
insert into category_details(detail, category_id) values ('mule', '5');
insert into category_details(detail, category_id) values ('ostryg', '5');
insert into category_details(detail, category_id) values ('muszle', '5');
insert into category_details(detail, category_id) values ('małże', '5');
insert into category_details(detail, category_id) values ('kalmar', '5');
insert into category_details(detail, category_id) values ('ośmior', '5');
insert into category_details(detail, category_id) values ('cielę', '6');
insert into category_details(detail, category_id) values ('jagnię', '7');
insert into category_details(detail, category_id) values ('baran', '8');
insert into category_details(detail, category_id) values ('sarn', '9');
insert into category_details(detail, category_id) values ('zając', '9');
insert into category_details(detail, category_id) values ('dzik', '9');
insert into category_details(detail, category_id) values ('jele', '9');
insert into category_details(detail, category_id) values ('dzicz', '9');
insert into category_details(detail, category_id) values ('rosół', '10');
insert into category_details(detail, category_id) values ('barszcz', '10');
insert into category_details(detail, category_id) values ('żurek', '10');
insert into category_details(detail, category_id) values ('zupa', '10');
insert into category_details(detail, category_id) values ('chłodnik', '10');
insert into category_details(detail, category_id) values ('krupnik', '10');
insert into category_details(detail, category_id) values ('krem', '10');
insert into category_details(detail, category_id) values ('miso', '10');
insert into category_details(detail, category_id) values ('tom yam', '10');
insert into category_details(detail, category_id) values ('kapuśniak', '10');
insert into category_details(detail, category_id) values ('harira', '10');
insert into category_details(detail, category_id) values ('forszmak', '10');
insert into category_details(detail, category_id) values ('laksa', '10');
insert into category_details(detail, category_id) values ('kwaśnica', '10');
insert into category_details(detail, category_id) values ('gazpacho', '10');
insert into category_details(detail, category_id) values ('caldo', '10');
insert into category_details(detail, category_id) values ('po bretońsku', '10');
insert into category_details(detail, category_id) values ('grochówka', '10');
insert into category_details(detail, category_id) values ('minestrone', '10');
insert into category_details(detail, category_id) values ('forszmak', '10');
insert into ingredient_details(name, receipe, shop_section_id) values ('pierś z kurczaka', true, '2');
insert into ingredient_details(name, receipe, shop_section_id) values ('udka z kurczaka', true, '2');
insert into ingredient_details(name, receipe, shop_section_id) values ('schab', true,'2');
insert into ingredient_details(name, receipe, shop_section_id) values ('szynka', true,'2');
insert into ingredient_details(name, receipe, shop_section_id) values ('polędwiczki wieprz.', true,'2');
insert into ingredient_details(name, receipe, shop_section_id) values ('żeberka wieprz.', true,'2');
insert into ingredient_details(name, receipe, shop_section_id) values ('karkówka wieprz.', true,'2');
insert into ingredient_details(name, receipe, shop_section_id) values ('marchewka', true,'3');
insert into ingredient_details(name, receipe, shop_section_id) values ('cebula', true,'3');
insert into ingredient_details(name, receipe, shop_section_id) values ('tymianek', true,'8');
insert into ingredient_details(name, receipe, shop_section_id) values ('pomidor', true,'3');
insert into ingredient_details(name, receipe, shop_section_id) values ('przecier pomidorowy', true,'17');
insert into ingredient_details(name, receipe, shop_section_id) values ('koncentrat pomidorowy', true,'17');
insert into ingredient_details(name, receipe, shop_section_id) values ('mleko', true,'4');
insert into ingredient_details(name, receipe, shop_section_id) values ('oliwki czarne', true,'17');
insert into ingredient_details(name, receipe, shop_section_id) values ('chleb', true,'1');
insert into ingredient_details(name, receipe, shop_section_id) values ('masło', true,'4');
insert into ingredient_details(name, receipe, shop_section_id) values ('parówki', true,'2');
insert into ingredient_details(name, receipe, shop_section_id) values ('piwo', true,'10');
insert into ingredient_details(name, receipe, shop_section_id) values ('wino', true,'10');
insert into ingredient_details(name, receipe, shop_section_id) values ('ziemniaki', true,'3');
insert into ingredient_details(name, receipe, shop_section_id) values ('włoszczyzna', true,'3');
insert into ingredient_details(name, receipe, shop_section_id) values ('banany', true,'3');
insert into ingredient_details(name, receipe, shop_section_id) values ('olej rzepakowy', true,'16');
insert into ingredient_details(name, receipe, shop_section_id) values ('avocado', true,'3');
insert into ingredient_details(name, receipe, shop_section_id) values ('ogórek', true,'3');
insert into ingredient_details(name, receipe, shop_section_id) values ('włoszczyzna', true,'3');
insert into ingredient_details(name, receipe, shop_section_id) values ('papryka czerwona', true,'3');
insert into ingredient_details(name, receipe, shop_section_id) values ('mleczko kokosowe', true,'12');
insert into ingredient_details(name, receipe, shop_section_id) values ('garam masala', true,'12');
insert into ingredient_details(name, receipe, shop_section_id) values ('ryż', true,'5');
insert into ingredient_details(name, receipe, shop_section_id) values ('kasza gryczana', true,'5');
insert into ingredient_details(name, receipe, shop_section_id) values ('jogurt naturalny', true,'4');
insert into ingredient_details(name, receipe, shop_section_id) values ('żółty ser', true,'4');

